import type { Metadata } from "next";
import { Header } from "./layout/Header";
import "./globals.css";
export const metadata: Metadata = {
  title: "DefaultNone",
  description: "Generated by default-none",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header></Header>
        {children}
        <footer></footer>
      </body>
    </html>
  );
}
